document.addEventListener("mouseup", debounce(handleMouseUp, 100));

function handleMouseUp(event) {
    if (
        event.target.tagName === "INPUT" ||
        event.target.tagName === "TEXTAREA" ||
        event.target.isContentEditable
    ) {
        const existingPopup = document.getElementById("ssstylish-popup");
        if (existingPopup) existingPopup.remove();

        const selection = window.getSelection();
        if (selection.rangeCount > 0 && !selection.isCollapsed) {
            const range = selection.getRangeAt(0);
            const rect = range.getBoundingClientRect();
            const selectedText = selection.toString();
            const popup = createPopup(rect, selectedText);

            document.body.appendChild(popup);

            popup.addEventListener("click", handlePopupClick, { once: true });
        }
    }
}

function createPopup(rect, selectedText) {
    const popup = document.createElement("div");
    popup.id = "ssstylish-popup";
    popup.style.top = `${rect.top + window.scrollY + 20}px`; // Adjust to avoid blocking text
    popup.style.left = `${rect.left + window.scrollX}px`;
    popup.style.position = "absolute"; // Ensure correct positioning
    popup.innerHTML = `
        <div id="ssstylish-button-container">
            ${createButtonsHtml()}
        </div>
    `;
    return popup;
}

function createButtonsHtml() {
    const styles = [
        { dataStyle: "boldSans", title: "Bold Sans", text: "𝗔𝗮" },
        { dataStyle: "italicSans", title: "Italic Sans", text: "𝘈𝘢" },
        { dataStyle: "boldItalicSans", title: "Bold Italic Sans", text: "𝘼𝙖" },
        { dataStyle: "boldSerif", title: "Bold Serif", text: "𝐀𝐚" },
        {
            dataStyle: "italicBoldSerif",
            title: "Italic Bold Serif",
            text: "𝑨𝒂",
        },
        { dataStyle: "typewriter", title: "Typewriter", text: "𝙰𝚊" },
        { dataStyle: "upsideDown", title: "Upside Down", text: "ɐ∀" },
        { dataStyle: "superscript", title: "Superscript", text: "ᴬᵃ" },
        { dataStyle: "subscript", title: "Subscript", text: "ₐₐ" },
    ];

    return styles
        .map(
            (style) => `
        <button data-style="${style.dataStyle}" title="${style.title}">${style.text}</button>
    `
        )
        .join("");
}

function handlePopupClick(e) {
    const button = e.target.closest("button");
    if (button) {
        const style = button.getAttribute("data-style");
        const selection = window.getSelection();
        const range = selection.getRangeAt(0);
        const currentText = selection.toString();
        const styledText = applyStyle(currentText, style);

        // Replace selected text with styled text
        range.deleteContents();
        range.insertNode(document.createTextNode(styledText));

        // Update clipboard
        navigator.clipboard
            .writeText(styledText)
            .catch((err) => console.error("Failed to copy text: ", err));

        // Insert styled text into target element
        const targetElement = e.target.closest(
            "input, textarea, [contenteditable]"
        );
        if (targetElement) {
            if (
                targetElement.tagName === "TEXTAREA" ||
                targetElement.tagName === "INPUT"
            ) {
                const value = targetElement.value;
                const start = targetElement.selectionStart;
                const end = targetElement.selectionEnd;
                targetElement.value =
                    value.slice(0, start) + styledText + value.slice(end);
            } else if (targetElement.isContentEditable) {
                const originalContent = targetElement.innerHTML;
                targetElement.innerHTML = originalContent.replace(
                    new RegExp(currentText, "g"),
                    styledText
                );
            }
        }

        // Hide popup
        const popup = document.getElementById("ssstylish-popup");
        if (popup) popup.style.display = "none";
    }
}

function applyStyle(text, style) {
    const styleMap = styles[style] || {};
    return text
        .split("")
        .map((char) => styleMap[char] || char)
        .join("");
}

function debounce(func, wait) {
    let timeout;
    return function (...args) {
        clearTimeout(timeout);
        timeout = setTimeout(() => func.apply(this, args), wait);
    };
}

const styles = {
    boldSans: {
        A: "𝗔",
        B: "𝗕",
        C: "𝗖",
        D: "𝗗",
        E: "𝗘",
        F: "𝗙",
        G: "𝗚",
        H: "𝗛",
        I: "𝗜",
        J: "𝗝",
        K: "𝗞",
        L: "𝗟",
        M: "𝗠",
        N: "𝗡",
        O: "𝗢",
        P: "𝗣",
        Q: "𝗤",
        R: "𝗥",
        S: "𝗦",
        T: "𝗧",
        U: "𝗨",
        V: "𝗩",
        W: "𝗪",
        X: "𝗫",
        Y: "𝗬",
        Z: "𝗭",
        a: "𝗮",
        b: "𝗯",
        c: "𝗰",
        d: "𝗱",
        e: "𝗲",
        f: "𝗳",
        g: "𝗴",
        h: "𝗵",
        i: "𝗶",
        j: "𝗷",
        k: "𝗸",
        l: "𝗹",
        m: "𝗺",
        n: "𝗻",
        o: "𝗼",
        p: "𝗽",
        q: "𝗾",
        r: "𝗿",
        s: "𝘀",
        t: "𝘁",
        u: "𝘂",
        v: "𝘃",
        w: "𝘄",
        x: "𝘅",
        y: "𝘆",
        z: "𝘇",
        0: "𝟬",
        1: "𝟭",
        2: "𝟮",
        3: "𝟯",
        4: "𝟰",
        5: "𝟱",
        6: "𝟲",
        7: "𝟯",
        8: "𝟴",
        9: "𝟵",
    },
    italicSans: {
        A: "𝘈",
        B: "𝘉",
        C: "𝘊",
        D: "𝘋",
        E: "𝘌",
        F: "𝘍",
        G: "𝘎",
        H: "𝘏",
        I: "𝘐",
        J: "𝘑",
        K: "𝘒",
        L: "𝘓",
        M: "𝘔",
        N: "𝘕",
        O: "𝘖",
        P: "𝘗",
        Q: "𝘘",
        R: "𝘙",
        S: "𝘚",
        T: "𝘛",
        U: "𝘜",
        V: "𝘝",
        W: "𝘞",
        X: "𝘟",
        Y: "𝘠",
        Z: "𝘡",
        a: "𝘢",
        b: "𝘣",
        c: "𝘤",
        d: "𝘥",
        e: "𝘦",
        f: "𝘧",
        g: "𝘨",
        h: "𝘩",
        i: "𝘪",
        j: "𝘫",
        k: "𝘬",
        l: "𝘭",
        m: "𝘮",
        n: "𝘯",
        o: "𝘰",
        p: "𝘱",
        q: "𝘲",
        r: "𝘳",
        s: "𝘴",
        t: "𝘵",
        u: "𝘶",
        v: "𝘷",
        w: "𝘸",
        x: "𝘹",
        y: "𝘺",
        z: "𝘻",
        0: "0",
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
        6: "6",
        7: "7",
        8: "8",
        9: "9",
    },
    boldItalicSans: {
        A: "𝘼",
        B: "𝘽",
        C: "𝘾",
        D: "𝘿",
        E: "𝙀",
        F: "𝙁",
        G: "𝙂",
        H: "𝙃",
        I: "𝙄",
        J: "𝙅",
        K: "𝙆",
        L: "𝙇",
        M: "𝙈",
        N: "𝙉",
        O: "𝙊",
        P: "𝙋",
        Q: "𝙌",
        R: "𝙍",
        S: "𝙎",
        T: "𝙏",
        U: "𝙐",
        V: "𝙑",
        W: "𝙒",
        X: "𝙓",
        Y: "𝙔",
        Z: "𝙕",
        a: "𝙖",
        b: "𝙗",
        c: "𝙘",
        d: "𝙙",
        e: "𝙚",
        f: "𝙛",
        g: "𝙜",
        h: "𝙝",
        i: "𝙞",
        j: "𝙟",
        k: "𝙠",
        l: "𝙡",
        m: "𝙢",
        n: "𝙣",
        o: "𝙤",
        p: "𝙥",
        q: "𝙦",
        r: "𝙧",
        s: "𝙨",
        t: "𝙩",
        u: "𝙪",
        v: "𝙫",
        w: "𝙬",
        x: "𝙭",
        y: "𝙮",
        z: "𝙯",
        0: "𝟎",
        1: "𝟏",
        2: "𝟐",
        3: "𝟑",
        4: "𝟒",
        5: "𝟓",
        6: "𝟔",
        7: "𝟕",
        8: "𝟖",
        9: "𝟗",
    },
    boldSerif: {
        A: "𝐀",
        B: "𝐁",
        C: "𝐂",
        D: "𝐃",
        E: "𝐄",
        F: "𝐅",
        G: "𝐆",
        H: "𝐇",
        I: "𝐈",
        J: "𝐉",
        K: "𝐊",
        L: "𝐋",
        M: "𝐌",
        N: "𝐍",
        O: "𝐎",
        P: "𝐏",
        Q: "𝐐",
        R: "𝐑",
        S: "𝐒",
        T: "𝐓",
        U: "𝐔",
        V: "𝐕",
        W: "𝐖",
        X: "𝐗",
        Y: "𝐘",
        Z: "𝐙",
        a: "𝐚",
        b: "𝐛",
        c: "𝐜",
        d: "𝐝",
        e: "𝐞",
        f: "𝐟",
        g: "𝐠",
        h: "𝐡",
        i: "𝐢",
        j: "𝐣",
        k: "𝐤",
        l: "𝐥",
        m: "𝐦",
        n: "𝐧",
        o: "𝐨",
        p: "𝐩",
        q: "𝐪",
        r: "𝐫",
        s: "𝐬",
        t: "𝐭",
        u: "𝐮",
        v: "𝐯",
        w: "𝐰",
        x: "𝐱",
        y: "𝐲",
        z: "𝐳",
        0: "𝟎",
        1: "𝟏",
        2: "𝟐",
        3: "𝟑",
        4: "𝟒",
        5: "𝟓",
        6: "𝟔",
        7: "𝟕",
        8: "𝟖",
        9: "𝟗",
    },
    italicBoldSerif: {
        A: "𝑨",
        B: "𝑩",
        C: "𝑪",
        D: "𝑫",
        E: "𝑬",
        F: "𝑭",
        G: "𝑮",
        H: "𝑯",
        I: "𝑰",
        J: "𝑱",
        K: "𝑲",
        L: "𝑳",
        M: "𝑴",
        N: "𝑵",
        O: "𝑶",
        P: "𝑷",
        Q: "𝑸",
        R: "𝑹",
        S: "𝑺",
        T: "𝑻",
        U: "𝑼",
        V: "𝑽",
        W: "𝑾",
        X: "𝑿",
        Y: "𝒀",
        Z: "𝒁",
        a: "𝒂",
        b: "𝒃",
        c: "𝒄",
        d: "𝒅",
        e: "𝒆",
        f: "𝒇",
        g: "𝒈",
        h: "𝒉",
        i: "𝒊",
        j: "𝒋",
        k: "𝒌",
        l: "𝒍",
        m: "𝒎",
        n: "𝒏",
        o: "𝒐",
        p: "𝒑",
        q: "𝒒",
        r: "𝒓",
        s: "𝒔",
        t: "𝒕",
        u: "𝒖",
        v: "𝒗",
        w: "𝒘",
        x: "𝒙",
        y: "𝒚",
        z: "𝒛",
        0: "𝟎",
        1: "𝟏",
        2: "𝟐",
        3: "𝟑",
        4: "𝟒",
        5: "𝟓",
        6: "𝟔",
        7: "𝟕",
        8: "𝟖",
        9: "𝟗",
    },
    typewriter: {
        A: "𝙰",
        B: "𝙱",
        C: "𝙲",
        D: "𝙳",
        E: "𝙴",
        F: "𝙵",
        G: "𝙶",
        H: "𝙷",
        I: "𝙸",
        J: "𝙹",
        K: "𝙺",
        L: "𝙻",
        M: "𝙼",
        N: "𝙽",
        O: "𝙾",
        P: "𝙿",
        Q: "𝚀",
        R: "𝚁",
        S: "𝚂",
        T: "𝚃",
        U: "𝚄",
        V: "𝚅",
        W: "𝚆",
        X: "𝚇",
        Y: "𝚈",
        Z: "𝚉",
        a: "𝚎",
        b: "𝚋",
        c: "𝚌",
        d: "𝚍",
        e: "𝚎",
        f: "𝚏",
        g: "𝚐",
        h: "𝚑",
        i: "𝚒",
        j: "𝚓",
        k: "𝚔",
        l: "𝚕",
        m: "𝚖",
        n: "𝚗",
        o: "𝚘",
        p: "𝚙",
        q: "𝚚",
        r: "𝚛",
        s: "𝚜",
        t: "𝚝",
        u: "𝚞",
        v: "𝚟",
        w: "𝚠",
        x: "𝚡",
        y: "𝚢",
        z: "𝚣",
        0: "𝟶",
        1: "𝟷",
        2: "𝟸",
        3: "𝟹",
        4: "𝟺",
        5: "𝟻",
        6: "𝟼",
        7: "𝟽",
        8: "𝟾",
        9: "𝟿",
    },
    upsideDown: {
        A: "∀",
        B: "B",
        C: "Ƨ",
        D: "Ԁ",
        E: "Ǝ",
        F: "Ⅎ",
        G: "Ϭ",
        H: "H",
        I: "I",
        J: "ſ",
        K: "ʞ",
        L: "˥",
        M: "M",
        N: "N",
        O: "O",
        P: "Ԛ",
        Q: "Ԛ",
        R: "ɹ",
        S: "S",
        T: "⊥",
        U: "∩",
        V: "ʌ",
        W: "M",
        X: "X",
        Y: "⅄",
        Z: "Z",
        a: "ɐ",
        b: "q",
        c: "ɔ",
        d: "p",
        e: "ǝ",
        f: "ɟ",
        g: "ƃ",
        h: "ɥ",
        i: "ᴉ",
        j: "ɾ",
        k: "ʞ",
        l: "˥",
        m: "ɯ",
        n: "u",
        o: "o",
        p: "d",
        q: "b",
        r: "ɹ",
        s: "s",
        t: "ʇ",
        u: "n",
        v: "ʌ",
        w: "ʍ",
        x: "x",
        y: "ʎ",
        z: "z",
        0: "0",
        1: "Ɩ",
        2: "ᄅ",
        3: "Ɛ",
        4: "ᔭ",
        5: "ϝ",
        6: "9",
        7: "ㄥ",
        8: "8",
        9: "6",
    },
    superscript: {
        A: "ᴬ",
        B: "ᴮ",
        C: "ᶜ",
        D: "ᴰ",
        E: "ᴱ",
        F: "ᴳ",
        G: "ᴳ",
        H: "ᴴ",
        I: "ᴵ",
        J: "ᴶ",
        K: "ᴷ",
        L: "ᴸ",
        M: "ᴹ",
        N: "ᴺ",
        O: "ᴼ",
        P: "ᴾ",
        Q: "Q",
        R: "ᴿ",
        S: "ˢ",
        T: "ᵀ",
        U: "ᵁ",
        V: "ᵛ",
        W: "ʷ",
        X: "ˣ",
        Y: "ʸ",
        Z: "ᶻ",
        a: "ᵃ",
        b: "ᵇ",
        c: "ᶜ",
        d: "ᵈ",
        e: "ᵉ",
        f: "ꜻ",
        g: "ᵍ",
        h: "ʜ",
        i: "ᵢ",
        j: "ʲ",
        k: "ᵏ",
        l: "ˡ",
        m: "ᵐ",
        n: "ⁿ",
        o: "ᵒ",
        p: "ᵖ",
        q: "ᵟ",
        r: "ʳ",
        s: "ˢ",
        t: "ᵗ",
        u: "ᵘ",
        v: "ᵥ",
        w: "ʷ",
        x: "ˣ",
        y: "ʸ",
        z: "ᶻ",
        0: "⁰",
        1: "¹",
        2: "²",
        3: "³",
        4: "⁴",
        5: "⁵",
        6: "⁶",
        7: "⁷",
        8: "⁸",
        9: "⁹",
    },
    subscript: {
        A: "ₐ",
        B: "ₑ",
        C: "C",
        D: "D",
        E: "ₑ",
        F: "F",
        G: "G",
        H: "H",
        I: "ᵢ",
        J: "J",
        K: "K",
        L: "L",
        M: "M",
        N: "N",
        O: "O",
        P: "P",
        Q: "Q",
        R: "ᵣ",
        S: "ₛ",
        T: "ₜ",
        U: "ᵤ",
        V: "V",
        W: "W",
        X: "X",
        Y: "Y",
        Z: "Z",
        a: "ₐ",
        b: "b",
        c: "c",
        d: "d",
        e: "ₑ",
        f: "f",
        g: "g",
        h: "h",
        i: "ᵢ",
        j: "j",
        k: "k",
        l: "l",
        m: "m",
        n: "n",
        o: "o",
        p: "p",
        q: "q",
        r: "ᵣ",
        s: "ₛ",
        t: "ₜ",
        u: "ᵤ",
        v: "v",
        w: "w",
        x: "x",
        y: "y",
        z: "z",
        0: "₀",
        1: "₁",
        2: "₂",
        3: "₃",
        4: "₄",
        5: "₅",
        6: "₆",
        7: "₇",
        8: "₈",
        9: "₉",
    },
};
